FactoryBot.define do
  factory :application do
    name { "Test Application" }
    chats_count { 0 }
    # The token attribute is automatically generated by has_secure_token, so you typically do not need to set it here.
  end
end
